### ISSUE TITLE
How to pull portal dose images automatically from database?

### ISSUE THREAD

**Issue by jazb83** [VarianAPIs/Varian-Code-Samples#15]
I am currently working in a “In-vivo EPID dosimetry” project, and we need to pull the portal dose images from Aria. We have been doing it manually and a patient by patient basis, but it has become an inconvenient now because our database has increased considerably. So, we want to develop an application to do it automatically using ESAPI (or other tools available).

I have been trying to find some information-examples about it in different places:

"Scripting API documentation"
"-Code examples ( http://www.carlosjanderson.com/ )"
"evilDicom ( http://rexcardan.github.io/Evil-DICOM/api/index.html )"
"Esapix Extension ( https://github.com/rexcardan/ESAPIX )"
"Code Example to pull dicom images ( https://github.com/VarianAPIs/Varian-Code-Samples/wiki/Scripting-the-Varian-DICOM-DB-Daemon-with-ESAPI )"
"Different varian code examples ( https://github.com/VarianAPIs/Varian-Code-Samples )"

But it seems that I am out of luck.

Ant help is truly appreciated.

**Comment by fizxmike** [comment]
@mattcschmidt, can you comment on this? Can the portal dose images be queried through DICOM interface?

**Comment by jazb83** [comment]
Hello guys,

Thank you for following the issue. Yes, they can. I have been retrieving the images using the DCMTK from command prompt (cmd). I will write the solution here later. I have not gone through: 
        Varian-Code-Samples/Eclipse Scripting API/plugins/GetDicomCollection.cs
     but the command is similar to the ones you have there.

Cheers

**Comment by mattcschmidt** [comment]
Right, I think this is definitely possible, though I think it may be difficult to determine if the image is an integrated image type. I'm thinking that the GetDicomCollection script will simply pull every image associated with that patient without some modification.

**Comment by jazb83** [comment]
I am assuming that you already set up the Varian's DICOM connectivity. The Varian DB service is configured so it can be remotely controlled by the DCMTK package to send DICOM objects via C-MOVE to the Varian File Service ( see https://github.com/jazb83/DICOM-Scripting/blob/master/DicomScriptingEclipse.pdf)

In order to pull the portal dose images ( "0008,0060=RTIMAGE"), you must know the SeriesInstanceUIDs ("0020,000e") for this modality.

You can query them by executing the following command from DCMTK:

`findscu -v -aet DCMTK -aec VMSDBD 10.1.0.4 51402 -S -k “0008,0052=SERIES” -k “0010,0020=20042271” -k “0008,0060=RTDOSE” `

•	aet : Set my calling AET (DCMTK)
•	aec: Set called AET (VMSDBD)
•	aem = Set move destination AET (VMSFSD-OUT)
•	hostname of IP of DICOM peer (10.1.0.4)
•	tcp/ip port number of peer (51402)
•	S =Query information model STUDY
•	0008,0052 = QueryRetrieveLevel (Series)
•      0010,0020 = PatientID
•	0008,0060 = RTDOSE modality

if RTDOSE series exist, you should have an output like this:

 ---------------------------
I: Find Response: 1 (Pending)
I:
I: # Dicom-Data-Set
I: # Used TransferSyntax: Little Endian Implicit
I: (0008,0005) CS [ISO_IR 192]                             #  10, 1 SpecificCharacterSet
I: (0008,0052) CS [SERIES]                                 #   6, 1 QueryRetrieveLevel
I: (0008,0054) AE [VMSDBD]                                 #   6, 1 RetrieveAETitle
I: (0008,0060) CS [**RTIMAGE** ]                               #   8, 1 Modality
I: (0010,0020) LO [20042271]                               #   8, 1 PatientID
I: (0020,000e) UI [**1.2.246.352.62.2.5432612013526007277.3213210371212185013**] #  56, 1 SeriesInstanceUID
I: (0020,0011) IS [3 ]                                     #   2, 1 SeriesNumber
I:
I: ---------------------------
I: Find Response: 2 (Pending)
I:
I: # Dicom-Data-Set
I: # Used TransferSyntax: Little Endian Implicit
I: (0008,0005) CS [ISO_IR 192]                             #  10, 1 SpecificCharacterSet
I: (0008,0052) CS [SERIES]                                 #   6, 1 QueryRetrieveLevel
I: (0008,0054) AE [VMSDBD]                                 #   6, 1 RetrieveAETitle
I: (0008,0060) CS [**RTIMAGE** ]                               #   8, 1 Modality
I: (0010,0020) LO [20042271]                               #   8, 1 PatientID
I: (0020,000e) UI [**1.2.246.352.62.2.4896469073873812422.1696007591822704785**] #  56, 1 SeriesInstanceUID
I: (0020,0011) IS [3 ]                                     #   2, 1 SeriesNumber
I:
I: ---------------------------

Then, you can pull the images with the following command:
`
movescu -v -d -aet DCMTK -aec VMSDBD -aem VMSFSD-OUT -S -k "0008,0052=SERIES" -k "0020,000E=**1.2.246.352.62.2.5432612013526007277.3213210371212185013**"  10.1.0.4 51402`

•	aem = Set move destination AET (VMSFSD-OUT)

Unfortunately, you will have to repeat the previous command for every serie UIDS. An inconvenient if you have a lot of of RTIMAGE series. Hopefully, I will implement a script in the coming days to pull them automatically.

These two reference are a good place to start with:

- https://github.com/VarianAPIs/DICOM_Communication_101/blob/master/DICOM_Communication_101/CMoveTutorial2.cs

- https://github.com/VarianAPIs/Varian-Code-Samples/blob/master/Eclipse%20Scripting%20API/plugins/GetDicomCollection.cs
