### ISSUE TITLE
Script Approval during development

### ISSUE THREAD

**Issue by jbaker31** [VarianAPIs/Varian-Code-Samples#17]
Hi,
I am creating a writable script, but am having an issue with having to approve the script every time I make a slight change to the program.  When the script is in development this is a major issue, because it requires constant reapproval.

Is there a work around?
Thanks,
Jamie

**Comment by jwtx1980** [comment]
Hi Jamie, if your on a test box you should be able to set it to be in research mode.  This will allow you to run the scripts with out going through the approval process for each interation.

Best
Justin

**Comment by fizxmike** [comment]
There is no work-around if you are on a clinical system; slight changes necessarily require re-approval. As mentioned above, If you are developing on a separate system, like a test box, you can put the system into research mode (check box) under RT Administration work-space -> System and Facilities -> System Properties:
 
![image](https://user-images.githubusercontent.com/4626398/52495679-12625100-2b97-11e9-8f07-307223554509.png)
