### ISSUE TITLE
Some issues in Create Verification plan.cs 

### ISSUE THREAD

**Issue by starplanet18** [VarianAPIs/Varian-Code-Samples#2]
Hi,
I am using Varian Eclipse V13.6, when i try to compile this script via visual studio 2017 community edition, I found the error in the line : 130
verificationPlan.SetPrescription(numberOfFractions, verifiedPlan.DosePerFraction, treatmentPercentage: 1.0);

Setprescription is not present in the scope of verifiedPlan and similar is the way with DosePerFraction and treatmentPercentage.

I replaced the above line with this

verificationPlan.UniqueFractionation.SetPrescription(numberOfFractions, verifiedPlan.UniqueFractionation.PrescribedDosePerFraction, prescribedPercentage: 1.0);

After that scripts compiled and build successfully with the warning message:
warning CS1668: Invalid search path 'D:\sybase\OCS-15_0\lib' specified in 'LIB environment variable' -- 'directory does not exist'

Can you please suggest me regarding above warning without resolving the warning issue I am unable to run the script through the eclipse.

when i tried this script to run on the Eclipse TPS which is connected to the Main Server whose database is not configured for research mode. I am unable to run the script. In the main TPS, I am not getting any warning message as above except "research Database".
Kindly give me the solution

Thanks

**Comment by fizxmike** [comment]
Sorry for the delay. Unfortunately, the "writable" features you are trying to use are not available in clinical mode until v15. I'm not sure about the lib path warning... Are you using the eclipse scripting wizard?

**Comment by fizxmike** [comment]
@starplanet18 What I think is happening is that the demo from the 2018 webinar (CreateVerificationPlan.cs) is based on eclipse 15.x, and there have been some breaking changes between 13.6 and 15.x. My suggestion is to [look at the code linked here](https://github.com/VarianAPIs/samples/tree/master/webinars%20%26%20workshops/Research%20Symposium%202015/Eclipse%20Scripting%20API/Projects/AutomatedPlanningDemo), since that was written (and should still run) in eclipse v13.6. Please let us know your progress!

**Comment by ItumelengS** [comment]
I have used the suggestion above but having adjusted the some of the functions. However when I run the script, it says the control points are invalid for a sliding window field, however when I run it the normal way there are no errors picked up?

**Comment by ItumelengS** [comment]
Ok. The issue above was caused by setup beams that were inserted. Once I deleted them the "control points" issue went away.

**Comment by fizxmike** [comment]
Thanks for the followup!
