### ISSUE TITLE
Check documents

### ISSUE THREAD

**Issue by ItumelengS** [VarianAPIs/Varian-Code-Samples#20]
Is it possible to write a script which checks for the documents type that have been uploaded in the patient database?

And also, I am trying to run one script and it tells I need my database to be research, I was wondering is it just an option to tick off or we have to create a database from scratch?

**Comment by mattcschmidt** [comment]
Hi ItumelengS,
It is possible to write a script that queries the documents from a patient using Document Service. This service is available via an API that is already installed on your system, but you can find a copy of it in this github repository. The repository location would be Eclipse Scripting API --> Projects-->Example RBE Report. The current script will post a document to ARIA, with which you can set the document type. You could use this knowledge of how this works along with the Document Service User Guide I uploaded to think about how to query the same API for document types.
[Varian Document Service User Guide.pdf](https://github.com/VarianAPIs/Varian-Code-Samples/files/2813434/Varian.Document.Service.User.Guide.pdf)

**Comment by mattcschmidt** [comment]
Regarding the second question, I'd like to know what version of Eclipse you're using to think of how to answer this question.

**Comment by ItumelengS** [comment]
We are using 13.7.

**Comment by jwtx1980** [comment]
If it's a writeable script(makes any modifications), I believe you have to be in research mode to run it prior to v15.

**Comment by ItumelengS** [comment]
Yes, I want to be in research mode, but how do I get there?

**Comment by ItumelengS** [comment]
I can use the TBOX in research mode, but I won't touch the main box after hearing the above. The script I had planned running was the CreateVerificationPlan, I am guessing the creation of the plan is the cause of this? So basically there is no way to create a useable plan unless you are 15.1 and above or you are in research mode? And please provide me with link on how to go into research mode for my TBOX.

**Comment by mattcschmidt** [comment]
Hi Itumeleng,

To get research mode on your TBOX, the first thing to check is whether or not you have the license. If you go into your Platform Portal and go to Licenses under Administrative services you should see a license called EclipseScriptingIfWriteAccess or sometimes maybe called EclipseScriptingResearchAPI (I can't remember but one of those). If you have that you can proceed to the next step, but if not, you'll have to contact Varian to get the license.

Once you have that, you may go to RT Administration in the System and Facilities Workspace. In that workspace you'll find a checkbox that is labelled "Database in Research Mode" if this is checked, you can use write-enabled scripting. If you want to test Write-enabled scripting, the Eclipse Scripting API Reference Guide on MyVarian has an example script you can run as a single file plugin to test the writeable functionality.

**Comment by ItumelengS** [comment]
Nope, it seeks like we do not have the license, and if it's for purchase I doubt our department would buy it. But thanks for the information.
