### ISSUE TITLE
VMS.TPS.PlanSumReporter

### ISSUE THREAD

**Issue by ItumelengS** [VarianAPIs/Varian-Code-Samples#21]
I am getting an error, "PlanSumReporter" does not exist in the namespace "VMS.TPS". Eclipse v13.7

**Comment by fizxmike** [comment]
It looks like you are using a sample but forgot to include a file:
https://github.com/VarianAPIs/Varian-Code-Samples/blob/d258640c688fff8cbda862861f24e32f7f5513fb/Eclipse%20Scripting%20API/projects/PlanQualityMetrics/PQMReporter.cs
