### ISSUE TITLE
Accessing gamma results from portal imaging

### ISSUE THREAD

**Issue by fxarnaud** [VarianAPIs/Varian-Code-Samples#22]
Dear all,
I'd like to know if there is a simple way of accessing gamma results calculated from portal imaging application.
If not (as I think it is), I guess that I have to calculate gamma index by my own, I mean hardcoding it? 
Thanks in advance.

**Comment by fizxmike** [comment]
Maybe this will help...
```csharp
int frameIndex = 0;
ImageRT gammaImage = context.Analysis.GammaImage;
Frame gammaFrame = gammaImage.Frames[frameIndex];
ushort[,] pixelsGamma = new ushort[gammaFrame.XSize, gammaFrame.YSize];
gammaFrame.GetVoxels(0, pixelsGamma);

for (int y = 0; y < gammaFrame.YSize; y++) {
    for (int x = 0; x < gammaFrame.XSize; x++) {
        bool isGammaGtOne = gammaFrame.VoxelToDisplayValue(pixelsGamma[x, y]) > 1.0;
        // ... gather some stats on the frame here ...
    }
}
```

**Comment by mattcschmidt** [comment]
Hi fxarnaud,
I'm not sure if this is what you were thinking in this post, but your question got me thinking: What if you wanted to go back and probe your gamma results through old plans for say a retrospective study or something like that. So here, we could loop through patients normally and for each PDPlanSetup loop through the Beams, and probe the PDAnalysis for whether or not a gamma criteria was part of the analysis. If so, report the result. 
  ```
          foreach(PDBeam pdBeam in pdPlans.Beams)
            {
                PDAnalysis pdAnalysis = pdBeam.PortalDoseImages.Last().Analyses.OrderBy(x => x.CreationDate).LastOrDefault();
                if (pdAnalysis == null)
                {
                    Console.WriteLine($"{pdBeam.Id} has no Analysis");
                }
                else
                {
                    EvaluationTest gammaTest = pdAnalysis.EvaluationTests.FirstOrDefault(x => x.EvaluationTestKind == EvaluationTestKind.GammaAreaLessThanOne);
                    if (gammaTest == null)
                    {
                        Console.WriteLine($"{pdBeam.Id}:Gamma Area Less than One not applied");
                    }
                    else
                    {
                        double gammaResult = gammaTest.TestValue;
                        Console.WriteLine($"{pdBeam.Id}: Gamma = {gammaResult}");
                    }
                }
```

**Comment by fxarnaud** [comment]
Thanks mike and matt for your answers.
Actually my idea was exactly what matt said : a retrospective study for old plans.
I'll keep on working and try to implement it.
Thanks a lot !

**Comment by fxarnaud** [comment]
If I can humbly complete your post for future users I think you forgot
app.ClosePatient() at the end of the List loop.

Thanks again for your help !

**Comment by fizxmike** [comment]
Depends on the context, app.ClosePatient() isn't in scope for plugin scripts, but certainly a good practice for stand-alone executable.

**Comment by fxarnaud** [comment]
Sorry I confused with the piece of code matt kindly posted at reddit following my question.
https://www.reddit.com/r/esapi/comments/atdn66/retrospective_study_of_gamma_values_for_portal/
I supposed that in this case app.ClosePatient() was needed.
Thanks for the help again, I really appreciate.
