### ISSUE TITLE
Connection to ARIA DB via ESAPI plugin 

### ISSUE THREAD

**Issue by TillBoehlen** [VarianAPIs/Varian-Code-Samples#25]
I want to use the Entity Framework to access the ARIA database via an ESAPI plugin (following the example by C. Anderson: http://www.carlosjanderson.com/access-the-aria-database-with-the-entity-framework/)
When using a plugin runner to run the script the DB access works. However, when I launch the script as a plugin from Eclipse I get the error message: 'No connecntion string named 'AriaEntityContext' could be found in the application config file.'.
I assume this comes from the fact the startup project is different when launching as a plugin using a dll.
How can I make the plugin find the 'App.config' file? I already copied the same plugin file to all projects within my solution.

The connectionString line in the App.config file I use is the following:
<add name="AriaEntityContext" connectionString="data source=129.129.88.147;initial catalog=variansystem;persist security info=True;user id=reports;password=XXX;trustservercertificate=True;applicationintent=ReadOnly;MultipleActiveResultSets=True;App=EntityFramework" providerName="System.Data.SqlClient" />

Thanks for your help!

Best,

Till

**Comment by redcurry** [comment]
Hi Till,

Have you tried adding a copy of the App.config file (with the connection string) to the plug-in project?

**Comment by TillBoehlen** [comment]
Hi Carlos,

thanks for your quick reply!

As described in your blog post, I've copied the App.config file of the AriaEntities project to the start-up project I use for testing (your EclipsePlugInRunner.TestRunner) and also to the plug-in project (your EclipsePlugInRunner.TestScript) which should be the one which is called when ran as a plug-in.
(I also checked and the connection string is present in the *.dll.config which is created upon compilation)

This is the App.config file I use:
(At the moment I have still the hard-coded IP of our physical T-box as data source: 'data source=129.129.88.147' written everywhere. I guess for running on the virtual T-box system I will have to change to something like 'data source=localhost'. But this I couldn't test yet and the error message I receive should be different.)
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="mssqllocaldb" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
  <connectionStrings>
    <add name="AriaEntityContext" connectionString="data source=129.129.88.147;initial catalog=variansystem;persist security info=True;user id=reports;password=XXX;trustservercertificate=True;applicationintent=ReadOnly;MultipleActiveResultSets=True;App=EntityFramework" providerName="System.Data.SqlClient" />
</configuration>
`

**Comment by redcurry** [comment]
Hi Till,

I recreated your issue, and you're right---simply copying App.config to the plugin script project doesn't solve the problem. I will need to update my blog post with a full solution for plugin scripts.

Here's what you need to do. First, edit the `AriaEntityContext` constructor so that it looks like the following (i.e., explicitly pass in the `connectionString`):

    public AriaEntityContext(string connectionString) : base(connectionString)
    {
        Database.SetInitializer<AriaEntityContext>(null);
    }

Also, add the following dummy method to the `AriaEntityContext` class that fixes a "provider" issue (you will need to add the statement `using System.Data.Entity.SqlServer`):

    public void FixProviderIssue(SqlProviderServices service) { }

Now, when you create the `AriaEntityContext`, you'll need to pass in the connection string. You can extract this string from the project's App.config file. Here's the method that does it:

    private string GetConnectionString()
    {
        var asmPath = Assembly.GetExecutingAssembly().Location;
        var config = ConfigurationManager.OpenExeConfiguration(asmPath);
        return config.ConnectionStrings.ConnectionStrings["AriaEntityContext"].ConnectionString;
    }

You can now create the `AriaEntityContext` as follows:

    using (var ariaContext = new AriaEntityContext(GetConnectionString()))
    {
        // Your code here
    }

Please let me know if this solved the issue for you, and I'll add these new instructions to my blog post.

**Comment by TillBoehlen** [comment]
Hi Carlos,

Thanks for digging into this and your great support! Your solution worked for me nicely! 
A related question:
o Currently, accessing the data base with the EntityFramework (on the first DB call) is quite slow for me (I guess cause it loads the whole automatically created entity framework class library even though I just use a small part of it). Is there an easy way to make the access quicker, e.g. by just loading the really needed parts?

Cheers, Till

**Comment by rpascal** [comment]
@TillBoehlen @redcurry Do either of you by chance have an existing project with this implementation on GitHub that I could use as reference?  It would be very beneficial to have an actual project to look at.

Thanks, Ryan

**Comment by redcurry** [comment]
@TillBoehlen Is is the library loading that's slow or the database loading? If it's the database, you can delete any property that you don't need from the Entity class. That will cut down on the amount of data it needs to load from the database.

@rpascal Are you looking for an example of an ESAPI binary plug-in script or a standalone app that uses the EntityFramework?

**Comment by rpascal** [comment]
Either/Both would be helpful as long as there is the Entity Framework integration for connecting to ARIA.
