### ISSUE TITLE
CreateVerificationPlan.cs

### ISSUE THREAD

**Issue by patm95** [VarianAPIs/Varian-Code-Samples#39]
Hello all.  Relatively new to scripting.  Have some programming experience.  I can not load the .sln file or the .csproj files in MS visual studios.  I have 2019 community edition.  I have tried running the .cs file in Eclipse, but get many errors.  We have v15.6 Eclipse.  Any pointers would be appreciated.  Thank you.

**Comment by joecastelo** [comment]
You cannot run the .cs because in 15.6, you need to compile it in a binary script with ScriptName.esapi.dll assembly name (Go To Project Solution and change it there to ScripName.esapi if it is not already); Then press compile with x64 as CPU.
This code is only working for Sliding Window as far as I know.

**Comment by joecastelo** [comment]
If you're on research mode, you do not need to approve, but if you're on clinical you'll need.
I do not reccomend you to try writeable scripts that were not extensively checked on a clinical env.

**Comment by patm95** [comment]
> If you're on research mode, you do not need to approve, but if you're on clinical you'll need.
> I do not reccomend you to try writeable scripts that were not extensively checked on a clinical env.

Thank you for this advice.  I was able to get it to work as sliding window as you said.  However I was running into multiple problems with trying VMAT verificaiton plans.  Most commonly getting an error of too many control points.  However, it didn't seem to be consistent.

**Comment by joecastelo** [comment]
Ok! There's a post about creating VMAT Verification plans and they are not consistent. There are even dosimetric differences associated with them.

**Comment by patm95** [comment]
Oh good to know!  Sounds like this isn't ready for VMAT verification plans.  Maybe next version? ;-)

**Comment by joecastelo** [comment]
@patm95 We manage to do the VMAT QA works 
Reference to post #42
