### ISSUE TITLE
CreateVerificationPlan for VMAT Plan

### ISSUE THREAD

**Issue by joecastelo** [VarianAPIs/Varian-Code-Samples#42]
I recently started to customize CreateVerificationPlan.cs for VMAT Beams.
Everything works pretty good, until trying to CalculateDose.
It simply does not work, however if I try to calculate the dose in the verified plan it works fine.
Want to calculate dose with preset values using the CopyBeam function.

**Comment by joecastelo** [comment]
Just noted, if I Create the plan without calculating. Close the script and open another with the same command it works. Any ideas?

**Comment by tkstevens** [comment]
@joecastelo, can I assume you modified the `CopyBeam` function (in the `CreateVerificationPlan.cs` example) to replace `AddSlidingWindowBeam` with`AddVMATBeam`? I am able to calc the verification plan within the same script (no opening & closing necessary) using `plan.CalculateDose`, not `plan.CalculateDoseWithPresetValues`. However, I am running into the same issue posted here: https://github.com/VarianAPIs/Varian-Code-Samples/issues/31#issue-432252436.

**Comment by joecastelo** [comment]
Yeah I did!
I think one way you can make it work would be to run an standalone after the creation of the plan.

**Comment by joecastelo** [comment]
But this is not elegant. And error prone.

**Comment by LDClark** [comment]
I think this solution works:  [CreateVerificationPlan](https://github.com/LDClark/CreateVerificationPlan).

It is not the most elegant solution, but it fixed the controlpoint issue for VMAT.  The version I had modified before wasn't applying the editable parameters to the beam, in the method CopyBeam().

This version does this:
-Add beam to verification plan, and apply machineparameters, metersetweights, collimatorangle, gantry angle, etc.
-Makes the treat plan and verif plan beam names the same
-Goes through each plan's beams and makes the editable parameters the same and applies them

I checked the control points after, and they match now.

Landon

**Comment by joecastelo** [comment]
Thanks @LDClark !!
Worked for me doing the
verification.GetEditableParameters() = originalbeam.GetEditableParameters()
And then changing the Isocenter.

**Comment by tkstevens** [comment]
@LDClark -- just as @joecastelo identified, the solution doesn't depend on beam ID matching, but rather depends on using `verificationBeam.ApplyParameters(originalBeam.GetEditableParameters())` instead of applying the modified `verificationBeam.GetEditableParameters()` (Varian's IMRT verification code example sent us a bit off track on that). Thus, you should be able to chop out lines 186, 196-201, and 213-218 from your CreateVerificationPlan.cs to make a simpler version that still works!

**Comment by tkstevens** [comment]
One last minor thing I can't figure out is how to give a verification plan a proper primary reference point. When I run code as discussed above, even when I include creation of a new "verification" ref pt right after `QAcourse.AddExternalPlanSetupAsVerificationPlan`, I end up with a newly created primary ref pt that seems to stem from an existing structure in the plan to be verified (e.g. "Eye_R_PRV"). Any thoughts @LDClark @joecastelo ?

**Comment by joecastelo** [comment]
@tkstevens That's true, it seems random.
For our Ionization Cam QA it is not a problem to have this ref point with random name.
Somehow we could substitue the reference point name, but i have not found any means to do that.

**Comment by LDClark** [comment]
@tkstevens @joecastelo That is much better.

Does your original plan have the beam id convention G 1, G 2, etc.?  If it doesn't have the default name, e.g. G130T0, G0T90, etc., would it have problems at line 207:

`if (verificationBeam.Id == beam.Id)`

verificationBeam sets to the default id upon adding, as far as we can tell.  I like the way you guys applied the parameters - for the purposes of creating a verification plan, we might not want to keep modifying the original plan.

Is there a way to add a beam to a plan, and immediately set the parameters?  We could only apply it after the creation of the beam, but was left with two sets of IEnumerable<Beam> and had to come up with a way of going though them consistently and applying the editableparameters.

Where would you place the reference point, at isocenter?  Related to that issue, I end up with lots of extra verification structuresets.  It would be nice to keep that to a minimum on the clinical plans.

**Comment by joecastelo** [comment]
Answering your question. 
I am not renaming the fields with this pattern, just the fields original names, we have aria, so it aint a problem.
The reference point staying at a our user origin. The center point of the phantom.
If you do a function to apply the parameters after creating the beam and wrap it around in one function you can get this result, i havent tried, going by your == id method.
You can manage around the SS multiplication by just before copying SS test  if there is a structureset in the patient that matches the SS Id that you are looking for.

**Comment by LDClark** [comment]
I updated [CreateVerificationPlan](https://github.com/LDClark/CreateVerificationPlan).

This version:
-Names the verification fields to match the original plan (doesn't change the original plan)
-Looks for existing QA images so it won't import new ones
-Works on IMRT CalculateDoseWithPresetValues() using and VMAT using CalculateDose();

Still not perfect but open to suggestions.

**Comment by patm95** [comment]
Thank you for all your work on this!  I got it to run on my box, but the MU/Deg and Dose Rate still do not match and the final MU is different from the clinical plan.  Is there something I am missing?  Thank you!!

**Comment by avalgoma** [comment]
Many thanks for all your help. I follow this thread with a lot of interest.

As patm95 above, I got it to run on my tbox fot Truebeam and VMAT, but the MU/Deg, Dose Rate, MU/Arc do not match with the clinical plan :(

Best regards.

**Comment by LDClark** [comment]
I'm still seeing the same thing.

'var editableParams = beam.GetEditableParameters();
verificationBeam.ApplyParameters(editableParams);
`
Will give you the correct VMAT beam, _but_ it will change everything back to the original plan.  Isocenter, tableangle, collimatorangle, etc.  Tableangle and collimatorangle are read only.

'var editableParams = verificationBeam.GetEditableParameters();
 for (int n = 0; n < beam.ControlPoints.Count(); n++)
 {
editableParams.ControlPoints.ElementAt(n).LeafPositions = beam.ControlPoints.ElementAt(n).LeafPositions;
 editableParams.ControlPoints.ElementAt(n).JawPositions = beam.ControlPoints.ElementAt(n).JawPositions;
 }
verificationBeam.ApplyParameters(editableParams);'
Will give you the incorrect VMAT beam, but will keep the parameters from verificationPlan.AddVMATBeam().

Does everyone else see the same thing?

**Comment by patm95** [comment]
I'm sorry, I am somewhat confused.

When you say the correct VMAT beam, do you mean the correct MU per beam and
per degree?

When I ran the script on my VMAT plan, I got the same gantry and colimator
angles as the clinical plan (exactly what I wanted/expected).  All of the
beam geometry was correct.  But the MU on each beam was off slightly and
the MU/degree and dose rate was slightly varied from the clinical plan.f

Thank you!

**Comment by avalgoma** [comment]
Good morning everbody.

I run the script this morning again, but now on another VMAT plan in a different patient. And it worked correctly!!! Exactly the same treatment plan was copyied and calculated on our QA Phantom.

Why does CreateVerificationPlan work with this patient now?

I noticed that the plan I'd tried yesterday is a little bit strange. If you check the plan 178 control points you see things like this:

Índice	Peso Meterset	X1 [cm]	X2 [cm]	Y1 [cm]	Y2 [cm]	Gantry Rtn [°]	Tasa de la dosis  [UM/min]	Velocidad gantry  [grados/s]	UM/Deg
1	0.0000	-6.2	+5.1	-9.0	+9.0	179.0			
2	0.0019	-6.2	+5.2	-9.0	+9.0	178.0	115.313	6.000	0.320
3	0.0058	-6.2	+5.2	-9.0	+9.0	175.9	115.313	6.000	0.320
4	0.0096	-6.2	+5.2	-9.0	+9.0	173.9	115.313	6.000	0.320
5	0.0135	-6.2	+5.2	-9.0	+9.0	171.9	115.313	6.000	0.320
6	0.0173	-6.0	+5.2	-9.0	+9.0	169.8	115.313	6.000	0.320
7	0.0212	-6.0	+5.2	-9.0	+9.0	167.8	115.313	6.000	0.320
8	0.0250	-6.0	+5.2	-9.0	+9.0	165.8	115.313	6.000	0.320
9	0.0289	-6.0	+5.2	-9.0	+9.0	163.7	115.313	6.000	0.320
10	0.0325	-5.9	+5.5	-9.0	+9.0	161.7	108.693	6.000	0.302
11	0.0362	-5.9	+5.5	-9.0	+9.0	159.7	108.693	6.000	0.302
12	0.0398	-5.9	+5.5	-9.0	+9.0	157.6	108.693	6.000	0.302
13	0.0434	-6.0	+5.5	-9.0	+9.0	155.6	108.693	6.000	0.302
14	0.0472	-6.0	+5.7	-9.0	+9.0	153.6	111.954	6.000	0.311
15	0.0509	-6.0	+5.7	-9.0	+9.0	151.5	111.954	6.000	0.311
16	0.0546	-6.0	+5.7	-9.0	+9.0	149.5	111.954	6.000	0.311
17	0.0584	-6.0	+5.6	-9.0	+9.0	147.5	111.954	6.000	0.311
18	0.0633	-6.0	+5.7	-9.0	+9.0	145.4	148.439	6.000	0.412
19	0.0683	-6.0	+5.7	-9.0	+9.0	143.4	148.439	6.000	0.412
20	0.0733	-6.0	+5.6	-9.0	+9.0	141.4	148.439	6.000	0.412
21	0.0782	-6.2	+5.6	-9.0	+9.0	139.3	148.439	6.000	0.412
22	0.0833	-6.0	+5.6	-9.0	+9.0	137.3	152.754	6.000	0.424
23	0.0884	-6.0	+5.6	-9.0	+9.0	135.3	152.754	6.000	0.424
24	0.0935	-6.0	+5.6	-9.0	+9.0	133.2	152.754	6.000	0.424
25	0.0986	-6.0	+5.6	-9.0	+9.0	131.2	152.754	6.000	0.424
26	0.1028	-5.7	+5.5	-9.0	+9.0	129.2	123.980	6.000	0.344
27	0.1069	-5.6	+6.2	-9.0	+9.0	127.1	123.980	6.000	0.344
28	0.1069	-5.4	+6.1	-9.0	+9.0	125.1	-	6.000	-
29	0.1069	-5.3	+5.9	-9.0	+9.0	123.1	-	6.000	-
30	0.1069	-5.2	+5.8	-9.0	+9.0	121.0	-	6.000	-
31	0.1069	-5.1	+5.7	-9.0	+9.0	119.0	-	6.000	-
32	0.1069	-5.0	+5.6	-9.0	+9.0	117.0	-	6.000	-
33	0.1069	-4.9	+5.4	-9.0	+9.0	114.9	-	6.000	-
34	0.1069	-4.7	+5.3	-9.0	+9.0	112.9	-	6.000	-
35	0.1069	-4.6	+5.2	-9.0	+9.0	110.9	-	6.000	-
36	0.1069	-4.5	+5.0	-9.0	+9.0	108.8	-	6.000	-
37	0.1069	-4.4	+4.9	-9.0	+9.0	106.8	-	6.000	-
38	0.1069	-4.3	+4.8	-9.0	+9.0	104.8	-	6.000	-
39	0.1069	-4.2	+4.7	-9.0	+9.0	102.7	-	6.000	-
40	0.1069	-4.1	+4.5	-9.0	+9.0	100.7	-	6.000	-
41	0.1069	-4.0	+4.4	-9.0	+9.0	98.7	-	6.000	-
42	0.1069	-3.9	+4.3	-9.0	+9.0	96.6	-	6.000	-
43	0.1069	-3.8	+4.1	-9.0	+9.0	94.6	-	6.000	-
44	0.1069	-3.7	+4.0	-9.0	+9.0	92.6	-	6.000	-
45	0.1069	-3.6	+3.9	-9.0	+9.0	90.5	-	6.000	-
46	0.1069	-3.5	+3.9	-9.0	+9.0	88.5	-	6.000	-
47	0.1069	-3.6	+3.9	-9.0	+9.0	86.4	-	6.000	-
48	0.1095	-3.8	+3.7	-9.0	+9.0	84.4	77.869	6.000	0.216
49	0.1147	-4.1	+3.7	-9.0	+9.0	82.4	155.543	6.000	0.432
50	0.1237	-4.4	+3.7	-9.0	+9.0	80.3	269.609	6.000	0.749
51	0.1327	-4.5	+3.7	-9.0	+9.0	78.3	269.609	6.000	0.749
52	0.1418	-4.0	+3.7	-9.0	+9.0	76.3	269.609	6.000	0.749
53	0.1508	-4.5	+3.7	-9.0	+9.0	74.2	269.609	6.000	0.749
54	0.1598	-4.4	+3.7	-9.0	+9.0	72.2	269.609	6.000	0.749
55	0.1688	-4.2	+3.7	-9.0	+9.0	70.2	269.609	6.000	0.749
56	0.1778	-4.0	+3.7	-9.0	+9.0	68.1	269.609	6.000	0.749
57	0.1868	-4.1	+3.7	-9.0	+9.0	66.1	269.609	6.000	0.749
58	0.1951	-4.2	+3.9	-9.0	+9.0	64.1	247.176	6.000	0.687
59	0.2033	-4.2	+4.0	-9.0	+9.0	62.0	247.176	6.000	0.687
60	0.2116	-4.3	+4.3	-9.0	+9.0	60.0	247.176	6.000	0.687
61	0.2198	-4.5	+4.2	-9.0	+9.0	58.0	247.176	6.000	0.687
62	0.2281	-4.5	+4.6	-9.0	+9.0	55.9	247.176	6.000	0.687
63	0.2363	-4.5	+4.8	-9.0	+9.0	53.9	247.176	6.000	0.687
64	0.2446	-4.6	+4.5	-9.0	+9.0	51.9	247.176	6.000	0.687
65	0.2529	-4.7	+4.8	-9.0	+9.0	49.8	247.176	6.000	0.687
66	0.2606	-5.0	+5.3	-9.0	+9.0	47.8	232.357	6.000	0.645
67	0.2684	-5.2	+5.4	-9.0	+9.0	45.8	232.357	6.000	0.645
68	0.2762	-4.8	+5.4	-9.0	+9.0	43.7	232.357	6.000	0.645
69	0.2839	-5.4	+4.9	-9.0	+9.0	41.7	232.357	6.000	0.645
70	0.2915	-5.5	+5.4	-9.0	+9.0	39.7	225.589	6.000	0.627
71	0.2990	-5.5	+5.4	-9.0	+9.0	37.6	225.589	6.000	0.627
72	0.3065	-5.6	+5.4	-9.0	+9.0	35.6	225.589	6.000	0.627
73	0.3141	-5.6	+5.4	-9.0	+9.0	33.6	225.589	6.000	0.627
74	0.3208	-5.8	+6.0	-9.0	+9.0	31.5	200.614	6.000	0.557
75	0.3275	-5.8	+6.5	-9.0	+9.0	29.5	200.614	6.000	0.557
76	0.3342	-5.8	+6.5	-9.0	+9.0	27.5	200.614	6.000	0.557
77	0.3409	-5.8	+6.9	-9.0	+9.0	25.4	200.614	6.000	0.557
78	0.3476	-6.0	+7.6	-9.0	+9.0	23.4	200.614	6.000	0.557
79	0.3543	-6.0	+7.7	-9.0	+9.0	21.4	200.614	6.000	0.557
80	0.3610	-6.0	+8.0	-9.0	+9.0	19.3	200.614	6.000	0.557
81	0.3677	-6.0	+8.1	-9.0	+9.0	17.3	200.614	6.000	0.557
82	0.3760	-6.3	+8.4	-9.0	+9.0	15.3	247.587	6.000	0.688
83	0.3842	-6.2	+8.5	-9.0	+9.0	13.2	247.587	6.000	0.688
84	0.3925	-6.2	+8.6	-9.0	+9.0	11.2	247.587	6.000	0.688
85	0.4008	-6.4	+8.8	-9.0	+9.0	9.2	247.587	6.000	0.688
86	0.4091	-6.5	+8.8	-9.0	+9.0	7.1	247.587	6.000	0.688
87	0.4173	-6.5	+8.9	-9.0	+9.0	5.1	247.587	6.000	0.688
88	0.4256	-6.5	+8.9	-9.0	+9.0	3.1	247.587	6.000	0.688
89	0.4339	-6.5	+8.9	-9.0	+9.0	1.0	247.587	6.000	0.688
90	0.4412	-6.7	+9.3	-9.0	+9.0	359.0	219.539	6.000	0.610
91	0.4485	-6.7	+9.3	-9.0	+9.0	356.9	219.539	6.000	0.610
92	0.4559	-6.7	+9.3	-9.0	+9.0	354.9	219.539	6.000	0.610
93	0.4632	-6.7	+9.3	-9.0	+9.0	352.9	219.539	6.000	0.610
94	0.4703	-6.8	+9.3	-9.0	+9.0	350.8	213.144	6.000	0.592
95	0.4775	-6.7	+9.3	-8.5	+9.0	348.8	213.144	6.000	0.592
96	0.4846	-6.9	+9.3	-8.5	+9.0	346.8	213.144	6.000	0.592
97	0.4917	-6.9	+9.3	-8.5	+9.0	344.7	213.144	6.000	0.592
98	0.5007	-7.2	+9.3	-8.5	+9.0	342.7	270.270	6.000	0.751
99	0.5098	-6.9	+9.3	-8.5	+9.0	340.7	270.270	6.000	0.751
100	0.5188	-6.4	+9.3	-8.5	+9.0	338.6	270.270	6.000	0.751
101	0.5278	-6.4	+9.3	-8.5	+9.0	336.6	270.270	6.000	0.751
102	0.5369	-6.5	+9.3	-8.5	+9.0	334.6	270.270	6.000	0.751
103	0.5459	-6.5	+9.3	-8.5	+9.0	332.5	270.270	6.000	0.751
104	0.5549	-6.5	+9.3	-8.5	+9.0	330.5	270.270	6.000	0.751
105	0.5640	-6.5	+9.3	-8.5	+8.5	328.5	270.270	6.000	0.751
106	0.5722	-6.6	+9.3	-8.0	+8.5	326.4	247.336	6.000	0.687
107	0.5805	-6.6	+9.3	-8.0	+8.5	324.4	247.336	6.000	0.687
108	0.5887	-6.6	+9.3	-8.0	+8.5	322.4	247.336	6.000	0.687
109	0.5970	-6.6	+9.3	-8.0	+8.5	320.3	247.336	6.000	0.687
110	0.6053	-6.7	+9.3	-8.0	+8.5	318.3	247.113	6.000	0.686
111	0.6135	-6.7	+9.3	-8.0	+8.5	316.3	247.113	6.000	0.686
112	0.6218	-7.5	+9.3	-8.0	+8.5	314.2	247.113	6.000	0.686
113	0.6300	-7.8	+9.3	-8.0	+8.0	312.2	247.113	6.000	0.686
114	0.6368	-8.2	+9.3	-8.0	+8.0	310.2	201.855	6.000	0.561
115	0.6435	-8.2	+9.3	-8.0	+8.0	308.1	201.855	6.000	0.561
116	0.6503	-8.2	+9.3	-8.0	+8.0	306.1	201.855	6.000	0.561
117	0.6570	-8.2	+9.2	-8.0	+8.0	304.1	201.855	6.000	0.561
118	0.6638	-8.3	+8.7	-8.0	+8.0	302.0	202.037	6.000	0.561
119	0.6705	-8.3	+8.5	-8.0	+8.0	300.0	202.037	6.000	0.561
120	0.6773	-8.3	+8.2	-8.0	+7.5	298.0	202.037	6.000	0.561
121	0.6840	-8.3	+7.7	-7.5	+7.5	295.9	202.037	6.000	0.561
122	0.6908	-8.3	+7.4	-7.5	+7.5	293.9	202.037	6.000	0.561
123	0.6975	-8.3	+7.4	-7.5	+7.5	291.9	202.037	6.000	0.561
124	0.7043	-8.3	+7.1	-7.5	+7.5	289.8	202.037	6.000	0.561
125	0.7110	-8.3	+7.2	-7.5	+7.5	287.8	202.037	6.000	0.561
126	0.7155	-8.3	+7.0	-7.5	+7.5	285.8	134.738	6.000	0.374
127	0.7180	-8.2	+7.8	-7.5	+7.0	283.7	75.283	6.000	0.209
128	0.7180	-8.2	+7.6	-7.5	+7.0	281.7	-	6.000	-
129	0.7180	-8.2	+7.5	-7.5	+7.0	279.7	-	6.000	-
130	0.7180	-8.3	+7.4	-7.5	+7.0	277.6	-	6.000	-
131	0.7180	-8.3	+7.3	-7.5	+7.0	275.6	-	6.000	-
132	0.7180	-8.3	+7.2	-7.5	+7.0	273.6	-	6.000	-
133	0.7180	-8.3	+7.1	-7.5	+7.0	271.5	-	6.000	-
134	0.7180	-8.3	+7.0	-7.5	+6.5	269.5	-	6.000	-
135	0.7180	-8.3	+7.0	-7.5	+6.5	267.4	-	6.000	-
136	0.7180	-8.3	+6.9	-7.5	+6.5	265.4	-	6.000	-
137	0.7180	-8.3	+6.9	-7.5	+6.5	263.4	-	6.000	-
138	0.7180	-8.3	+6.8	-7.5	+6.5	261.3	-	6.000	-
139	0.7180	-8.3	+6.8	-7.5	+6.5	259.3	-	6.000	-
140	0.7180	-8.3	+6.7	-7.5	+6.5	257.3	-	6.000	-
141	0.7180	-8.3	+6.8	-7.5	+6.5	255.2	-	6.000	-
142	0.7180	-8.3	+7.0	-7.5	+6.5	253.2	-	6.000	-
143	0.7180	-8.3	+7.2	-7.5	+6.5	251.2	-	6.000	-
144	0.7180	-8.3	+7.3	-7.5	+6.5	249.1	-	6.000	-
145	0.7180	-8.3	+7.5	-7.5	+6.5	247.1	-	6.000	-
146	0.7180	-8.3	+7.7	-7.5	+7.0	245.1	-	6.000	-
147	0.7180	-8.3	+7.9	-7.5	+7.0	243.0	-	6.000	-
148	0.7180	-8.3	+8.1	-8.0	+7.0	241.0	-	6.000	-
149	0.7180	-8.3	+8.2	-8.0	+7.0	239.0	-	6.000	-
150	0.7254	-8.3	+8.8	-8.0	+7.0	236.9	219.792	6.000	0.611
151	0.7396	-8.3	+8.8	-8.0	+7.0	234.9	426.396	6.000	1.184
152	0.7536	-8.3	+8.7	-8.0	+7.0	232.9	417.897	6.000	1.161
153	0.7660	-8.3	+8.1	-8.0	+7.5	230.8	371.218	6.000	1.031
154	0.7770	-8.3	+7.8	-8.0	+7.5	228.8	329.456	6.000	0.915
155	0.7880	-8.3	+8.0	-8.0	+7.5	226.8	329.456	6.000	0.915
156	0.7990	-8.3	+8.0	-8.0	+7.5	224.7	329.456	6.000	0.915
157	0.8100	-8.3	+8.0	-8.0	+7.5	222.7	329.456	6.000	0.915
158	0.8210	-8.2	+8.4	-8.0	+7.5	220.7	329.456	6.000	0.915
159	0.8320	-8.1	+8.5	-8.0	+7.5	218.6	329.456	6.000	0.915
160	0.8431	-8.0	+9.1	-8.5	+8.0	216.6	329.456	6.000	0.915
161	0.8541	-8.0	+9.0	-8.5	+8.0	214.6	329.456	6.000	0.915
162	0.8630	-8.0	+9.0	-8.5	+8.0	212.5	268.368	6.000	0.745
163	0.8720	-8.0	+9.0	-8.5	+8.0	210.5	268.368	6.000	0.745
164	0.8810	-7.7	+8.9	-8.5	+8.0	208.5	268.368	6.000	0.745
165	0.8899	-7.7	+9.1	-8.5	+8.0	206.4	268.368	6.000	0.745
166	0.8989	-7.3	+9.1	-8.5	+8.5	204.4	268.610	6.000	0.746
167	0.9079	-6.6	+9.0	-8.5	+8.5	202.4	268.610	6.000	0.746
168	0.9169	-5.8	+9.0	-8.5	+8.5	200.3	268.610	6.000	0.746
169	0.9258	-5.0	+9.0	-8.5	+8.5	198.3	268.610	6.000	0.746
170	0.9346	-5.1	+8.7	-8.5	+8.5	196.3	261.021	6.000	0.725
171	0.9433	-5.1	+8.7	-9.0	+8.5	194.2	261.021	6.000	0.725
172	0.9520	-5.2	+8.5	-9.0	+8.5	192.2	261.021	6.000	0.725
173	0.9607	-5.2	+8.5	-9.0	+8.5	190.2	261.021	6.000	0.725
174	0.9694	-5.1	+8.2	-9.0	+9.0	188.1	261.256	6.000	0.726
175	0.9782	-5.2	+8.2	-9.0	+9.0	186.1	261.256	6.000	0.726
176	0.9869	-5.2	+8.2	-9.0	+9.0	184.1	261.256	6.000	0.726
177	0.9956	-5.2	+8.2	-9.0	+9.0	182.0	261.256	6.000	0.726
178	1.0000	-5.2	+8.2	-9.0	+9.0	181.0	261.256	6.000	0.726

Some information is missing? Why? No dose rate, no UM/deg for some (many) control points? What does this mean?

The VMAT plan I've successfully checked this morning with  CreateVerificationPlan has no missing info within control points.

I hope this helps!!!

Many thanks for your support.

-- Agus

**Comment by LDClark** [comment]
@patm95 Does your script do something like

var editableParams = beam.GetEditableParameters(); verificationBeam.ApplyParameters(editableParams);

That should give you the "correct" control points, as in matching MU/min, Gantry Angle, in each meterset/index.  I updated the repository I linked above and it does that and should give you the same VMAT beam in the QA plan.

**Comment by joecastelo** [comment]
Using this line solves all the problems we had!

**Comment by joecastelo** [comment]
@patm95  @avalgoma  Worked for you guys ? 
Can we close the issue?

**Comment by patm95** [comment]
Hi all.  I discovered something interesting.  I did have that code in there that @LDClark mentioned.  However, I was running it on a plan that was previously optimized on v11.  I copied the plan, reoptimized in v15.6, ran the script and it worked fine!  I will continue to monitor this on other patients calculated on v15.6.

**Comment by patm95** [comment]
I may have spoke too soon.  I think the reason my new plan worked is because it was only 1 beam.  Every plan that I run multiple beams the MU vary.  Isocenter and all beam parameters stay the same.  I basically just took your script and modified it to use our QA phantom and still no dice.  We are on 15.6 if that makes any difference.

**Comment by patm95** [comment]
Sorry for all the comments, but I just noticed something else.  Seems like this script sets the normalization to 100% on the QA plan.  So if I optimize a plan and leave the normalization alone after it finishes, the script works fine.  However, if I normalize the plan after optimization, the QA plan will only reflect the MU of plan with no normalization.  If that makes sense?

**Comment by joecastelo** [comment]
Ok got it. 
For me it is working fine, but I havent batched multiple cases.
And they had no manual normalization.
From my pov, it is not possible for the script to access normalization.
As i said in #51 , as long as the manual and scripted plans are the same we are good here.

**Comment by patm95** [comment]
Great work to @LDClark .  I'd say from my experience it is working fine considering isocenter placement and segment weight.  Normalization could be another issue but seems like may not be solved with scripting.  I am fine with closing if everyone else is.  Great work again to @LDClark !

**Comment by patm95** [comment]
Hi all.  Just FYI I found a solution to the normalization.

I use this as the vmat calculation sequence:
double v = verificationPlan.PlanNormalizationValue = verifiedPlan.PlanNormalizationValue;  

Copies the normalization every time so far.  Working 100% for me right now.

**Comment by avalgoma** [comment]
Eureka, It works 100% for me as well!!!!!

Many thanks for your help.

-- Agus

**Comment by joecastelo** [comment]
Great Guys ! 
Closing the post !
Thank you for your work!

**Comment by asocoliuc** [comment]
Hi everybody,

I am new here and not experienced, but I am trying to get a verification plan with ESAPI for my IMRT and VMAT plans. I 've read your conversation here and got inspired. I got a working script generating verification plans only for plans that **do not** have the jaw tracking option activated (I do test on the TBox, I have two machines and jaw tracking active only for one machine). My  question: is this code part working for you when using jaw tracking:

var editableParams =originalBeam.GetEditableParameters();

for (int n = 0; n < originalBeam.ControlPoints.Count(); n++)
{
editableParams.ControlPoints.ElementAt(n).LeafPositions = originalBeam.ControlPoints.ElementAt(n).LeafPositions; 
editableParams.ControlPoints.ElementAt(n).JawPositions = originalBeam.ControlPoints.ElementAt(n).JawPositions;
}

verificationBeam.ApplyParameters(editableParams);

For me it does not work, I always get the same error: There were errors in beam parameters.
 Sincerely, I do not understand why, since the leafs ad jaw positions are read for each control point... The jaw tracking is the only difference between my two machines.  Does anyone have an idea? Thanks a lot.

Ani
