### ISSUE TITLE
Structure deviations

### ISSUE THREAD

**Issue by larpra** [VarianAPIs/Varian-Code-Samples#45]
Dear all,
We have developed an Eclipse API script that automatically creates structures based on commands in an XML template. We observe that structures created by the script and structures created manually using the ARIA Contouring module deviates slightly (up to about 1 mm). Can you explain why that happens and can we trust the structures created using Eclipse API scripting? We use “Default resolution” for all our structures. 
Thanks, Lars

**Comment by joecastelo** [comment]
Hello @larpra, here we are having the same issue. 
For the sake of comparing, instead of using crop, I tried to follow the steps that eclipse scripts needs to crop in the countoring module and the same result is achieved.

**Comment by larpra** [comment]
I have tried to replace crop by margin + boolean in Contouring . Generally this changes the volume but there is no perfect agreement with the script. I got an answer from Varian. It turns out that Eclipse is based on a VFC framework whereas Contouring is based on a CA framework. This is the cause of the deviations.
