### ISSUE TITLE
@patm95  @avalgoma  Worked for you guys ?

### ISSUE THREAD

**Issue by avalgoma** [VarianAPIs/Varian-Code-Samples#51]
@patm95  @avalgoma  Worked for you guys ? 
Can we close the issue?

_Originally posted by @joecastelo in https://github.com/VarianAPIs/Varian-Code-Samples/issues/42#issuecomment-581429249_

**Comment by avalgoma** [comment]
I see slight differences in MU sometimes, not always. However, I think these differences come from Eclipse itself because if you follow a create QA verification plan within Eclipse (not using scripting) not always MU are exactly the same as in verified plan. Why? I don't know.

Thanks.

**Comment by joecastelo** [comment]
Yeah as far as I know, if we get the same result as the manual creation it is working properly
