### ISSUE TITLE
ARIA/Aura SQL queries from Eclipse API Scripting

### ISSUE THREAD

**Issue by avalgoma** [VarianAPIs/Varian-Code-Samples#52]
Hi.

It is possible to query ARIA database from an Eclipse C# Script? I mean something like SELECT session_treatment_dates FROM DepartmentActivity;

Many thanks in advance.

-- Agus

**Comment by joecastelo** [comment]
Hello @avalgoma, in the last days we've tried to do this coneccting directly to the AriaDB, but is very difficult to perform some linking as easy as AURA.
Varian has recently launched ARIAAccess that is a RestAPI, that works like AURA. 
MyVarian has some content about it! 
I havent started yet to use it but seems promising.

**Comment by avalgoma** [comment]
Many thanks for your help.

Food for thought :-)

**Comment by mattcschmidt** [comment]
You can definitely access the ARIA database with C#. http://www.carlosjanderson.com/access-the-aria-database-with-the-entity-framework/
I would stick with Joe's comments. The ARIA Access API could hopefully help. What are you trying to get from the DB?
P.s. I'm doing a webinar on ARIA Access March 23rd so hopefully that should give some insight on how to use the service.

**Comment by avalgoma** [comment]
Great news!

I would like to connect Patient diagnosis (and other clinical notes) to Eclipse plans, for example.

Many thanks.
