### ISSUE TITLE
How to set Intermediate Dose in OptimizeVMAT(Common.Model.Types.OptimizationOptionsVMAT) ? 

### ISSUE THREAD

**Issue by MatGodRho** [VarianAPIs/Varian-Code-Samples#60]
Hello guys, 

Do you know how to set Intermediate Dose in OptimizeVMAT(Common.Model.Types.OptimizationOptionsVMAT) ? 

Thanks !

**Comment by BradBeeksma** [comment]
`    //Set optimiser to calc intermediate dose
            string MLCID = "MLC-3747";
            OptimizationOptionsVMAT options = new OptimizationOptionsVMAT(OptimizationIntermediateDoseOption.UseIntermediateDose, MLCID);
            Plan.OptimizeVMAT(options);`

**Comment by MatGodRho** [comment]
Awesome thanks!!
