### ISSUE TITLE
How to set Optimization Mode in OptimizeVMAT(Common.Model.Types.OptimizationOptionsVMAT) ? 

### ISSUE THREAD

**Issue by MatGodRho** [VarianAPIs/Varian-Code-Samples#61]
Hello guys, 

Do you know how to set Optimization Mode in OptimizeVMAT(Common.Model.Types.OptimizationOptionsVMAT) ? 

Thanks !!

**Comment by BradBeeksma** [comment]
Answered in #60

**Comment by MatGodRho** [comment]
Thanks !
