### ISSUE TITLE
Boolean operations on low/high resolution structures   

### ISSUE THREAD

**Issue by larpra** [VarianAPIs/Varian-Code-Samples#66]
A boolean operation on both a low and high resolution structure produces an error. Is there a workaround for manipulation of a combination of low and high resolution structures?

**Comment by Kiragroh** [comment]
Yes. Similar like without scripting you have to build extra structures to overcome this.

Here is a CodeSnippet from one of my scripts:

Structure body = listStructures.Where(x => !x.IsEmpty && x.DicomType.ToUpper().Equals("EXTERNAL") || x.Id.ToUpper().Equals("KÖRPER") || x.Id.ToUpper().Equals("BODY") || x.Id.ToUpper().Equals("OUTER CONTOUR")).FirstOrDefault();
            if (body == null)
            {
                MessageBox.Show("Unbekannte Körper-Struktur-Bezeichnung. Körper, Body oder Outer Contour.");
                return;
            }
            if (ptv.IsHighResolution == false)
            {
                hk_ring.SegmentVolume = hk_ring.And(body);
            }
            else
            {
                bodyHighRes.SegmentVolume = body.Margin(0);
                bodyHighRes.ConvertToHighResolution();
                hk_ring.SegmentVolume = hk_ring.And(bodyHighRes);
            }
            

            //============================
            // remove structures unneccesary for optimization
            //============================
            ss.RemoveStructure(ptv_3mm);
            ss.RemoveStructure(bodyHighRes);

**Comment by larpra** [comment]
Does it mean that you ensure that both structures are high resolution before the boolean operation?

**Comment by Kiragroh** [comment]
Yes otherwise you cannot perform a operation. Like I said, it is the same like in contouring if you make this manually.
If you have at least one highRes structure. All other structures have to be HighRes too.

**Comment by larpra** [comment]
Thanks at lot :=)
